name: parkgrid_y
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  uuid: ^4.5.1
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  firebase_database: ^11.2.0
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
